### ISSUE TITLE
Question about accessing recyclerview parent width

### ISSUE THREAD

**Issue by alvindizon** [dadouf/PagingImageGallery#1]
How can you access the parent's width in your `CarouselAdapter`? When I attempt to do something similar I get a `0`.

**Comment by dadouf** [comment]
@alvindizon The key in my case was to do it in onCreateViewHolder: https://github.com/dadouf/PagingImageGallery/blob/master/app/src/main/java/com/davidferrand/pagingimagegallery/recyclerview/vfinal/CarouselActivity.kt#L136 is this what you are doing? In the constructor wouldn't work because the parent isn't laid out yet.

**Comment by alvindizon** [comment]
@dadouf I'm also doing it in `onCreateViewHolder`. I think the difference is that you're doing everything within an Activity, so you get the correct width instantly. I'm doing it somewhere else, so I used a `ViewTreeObserver` in order to listen when the parent is laid out and thus the width would be correct. Thanks for answering my question! Awesome example you have here BTW, it's very helpful 💯
